// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package JsonPeople

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Company struct {
	_tab flatbuffers.Table
}

func GetRootAsCompany(buf []byte, offset flatbuffers.UOffsetT) *Company {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Company{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCompany(buf []byte, offset flatbuffers.UOffsetT) *Company {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Company{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Company) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Company) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Company) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Company) CatchPhrase() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Company) Bs() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CompanyStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CompanyAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func CompanyAddCatchPhrase(builder *flatbuffers.Builder, catchPhrase flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(catchPhrase), 0)
}
func CompanyAddBs(builder *flatbuffers.Builder, bs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bs), 0)
}
func CompanyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
