// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package JsonPeople

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type People struct {
	_tab flatbuffers.Table
}

func GetRootAsPeople(buf []byte, offset flatbuffers.UOffsetT) *People {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &People{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPeople(buf []byte, offset flatbuffers.UOffsetT) *People {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &People{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *People) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *People) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *People) People(obj *Person, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *People) PeopleLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PeopleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PeopleAddPeople(builder *flatbuffers.Builder, people flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(people), 0)
}
func PeopleStartPeopleVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PeopleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
